# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 9, 10, 14, 54, 28, 868000))),
            ],
        ),
    ]
