# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='1', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 14, 56, 52, 75000)),
        ),
    ]
