# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180910_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 14, 57, 49, 694000)),
        ),
    ]
