# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import items.upload_to_aws


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null='True', upload_to=items.upload_to_aws.upload_img)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null='True', upload_to=items.upload_to_aws.upload_img)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemCategory', to='items.Category')),
            ],
        ),
    ]
