# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 17:18
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
