# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
