# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null='True', upload_to='static/uploads'),
        ),
    ]
