# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180910_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
    ]
