# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutpage_contactdetails_hometext_landingtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='text',
            field=models.TextField(default='ewr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometext',
            name='text',
            field=models.TextField(default='q3r'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingtext',
            name='text',
            field=models.TextField(default='wegw'),
            preserve_default=False,
        ),
    ]
