# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 17:18
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180917_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='hometext',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='landingtext',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
