# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180917_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
